### ISSUE TITLE
"left as an exercise to the reader"?

### ISSUE THREAD

**Issue by RalfJung** [matthieu-m/ghost-cell#2]
I am a bit confused about which methods you refer to when you say they have been "left as an exercise to the reader". We have a complete and compiling implementation of the GhostCell API surface at https://gitlab.mpi-sws.org/FP/ghostcell/-/tree/master/ghostcell; is there anything missing there that you found is required for ghost-collections (and that cannot be implemented on top of public safe functions)?

**Comment by nickkuk** [comment]
Not sure about "left as an exercise to the reader", but [useful example with mpsc channels](https://gitlab.mpi-sws.org/FP/ghostcell/-/issues/3) would be interesting.

**Comment by RalfJung** [comment]
This seems unrelated, but thanks for pointing me to that issue that I had missed. I will respond there.

**Comment by jesnor** [comment]
Yes, please use/merge the source code from the paper authors. Currently this `GhostCell` doesn't implement `Sync` which prohibits one of the major advantages of it :)

**Comment by matthieu-m** [comment]
Hi @RalfJung,

I followed the implementation in the paper -- which leaves some methods unimplemented -- and there's no link to the repository in the paper (or at the very least, CTRL+F gitlab does return any hit).

I'm used to "useless" landing pages, and had completely missed that http://plv.mpi-sws.org/rustbelt/ghostcell/ _had_ a link to the repository -- I just went straight to the paper.

Sorry.

---

> is there anything missing there that you found is required for ghost-collections (and that cannot be implemented on top of public safe functions)?

On `GhostCell` directly. I purely implemented the interface presented in the paper and it was enough.

What I did need was coming up with the `GhostCursor`, to "hop" from one `GhostCell` to the next without keeping the token borrowed. I think it's viable, but...

---

Would you be interested in taking ownership of the ghost-cell crate and publish your code?

Or opening a PR to put your code in this crate if you prefer, so that contributions are clear?

I don't mind doing the work myself, and add a link to the gitlab repository, if that's what you prefer.

And thanks for coming up with this, it's really great.

**Comment by RalfJung** [comment]
> I followed the implementation in the paper -- which leaves some methods unimplemented -- and there's no link to the repository in the paper (or at the very least, CTRL+F gitlab does return any hit).

Yes, sorry for that. The draft paper was prepared to be submitted to a conference that requires papers to be anonymous so that reviewers cannot (easily) tell who the authors are. Therefore we cannot have any links to git repositories as that would clearly identify us. We just uploaded the same text to the website (enabling author names) without notable further edits. If the paper gets accepted, we will prepare a final version that will contain such links.

>  And thanks for coming up with this, it's really great.

I'm happy you like it. :) However, also see [this comment](https://www.reddit.com/r/rust/comments/n420cg/is_it_possible_to_write_overheadfree_cyclic/gx0a9an/?utm_source=reddit&utm_medium=web2x&context=3) -- I did not come up with this API, @pythonesque did.

> Would you be interested in taking ownership of the ghost-cell crate and publish your code?

I would be interested in working with you on maintaining this crate. Maintaining a production-usable crate takes time so I wouldn't mind your help with that. :)

However, also note that the [qcell crate](https://crates.io/crates/qcell) provides the `LCell` type that is, to my knowledge, equivalent to `GhostCell` (inspired by an early draft of the API that @pythonesque  posted on Reddit).

**Comment by RalfJung** [comment]
> What I did need was coming up with the GhostCursor, to "hop" from one GhostCell to the next without keeping the token borrowed. I think it's viable, but...

Ah, interesting. I will need to take a closer look at that API then.

**Comment by matthieu-m** [comment]
@RalfJung @jesnor I've just released 0.2.2:

- https://gitlab.mpi-sws.org/FP/ghostcell/-/tree/master/ghostcell is referenced as the proven implementation.
- The implementation in this crate has been aligned on the proven implementation, including adding the missing traits and loosening `T` (to `?Sized`) for some methods.
- I have added examples for each method, and generally buffed up the documentation.
- I have added extensive compile-fail test coverage.
- I have run the entire test-suite under Miri.

Turns out I had "guessed" right how the trivial methods were implemented -- there was no trick -- and therefore their implementation did not require changing, so the release is fully compatible with the previous release: it just allows more.
