### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by joonazan** [matthieu-m/ghost-cell#24]
I need the ?Sized improvements that have been added lately but there is no version with them yet.

**Comment by matthieu-m** [comment]
There is currently a soundness issue (see #23) on master which came about due to the ?Sized improvements.

The plan is therefore to _first_ understand better this issue, and how to address it, then implement a solution (or rollback the unsound implementations), and then, only when everything is working as expected, to release these improvements.

Please bear with us in the meantime.

---

If you wish to still use ghost-cell in its current state, it is possible for Cargo to refer to git repositories at specific revisions or tags. It will prevent publishing the crate on crates.io, but not working with it.

**Comment by matthieu-m** [comment]
A new version 0.2.3 was released, containing many improvements, and hopefully no new unsoundness.

With many thanks to @noamtashma for raising the soundness issues affecting `GhostBorrowMut`, and to @wackbyte for all the `?Sized` improvements, among others.

Enjoy!
