### ISSUE TITLE
`check_distinct` reports a false positive for ZSTs in certain cases

### ISSUE THREAD

**Issue by wackbyte** [matthieu-m/ghost-cell#31]
Because `Box` uses the same address for all alocated ZSTs, attempting to `borrow_mut` with two boxed `GhostCell`s of ZSTs results in an aliasing error.

```rs
GhostToken::new(|mut token| {
    let cell1 = Box::new(GhostCell::new(())); // 0x1

    let cell2 = Box::new(GhostCell::new(())); // 0x1

    let tuple = (&*cell1, &*cell2); // (0x1, 0x1)
    assert!(tuple.borrow_mut(&mut token).is_ok()); // panic!
});
```

This can also occur with `&GhostCell::new(())`/`&mut GhostCell::new(())` in release mode.

**Comment by matthieu-m** [comment]
How vexing...

This is somewhat self-inflicted from using inclusive ranges to detect distinct vs not distinct. This ends up losing the distinction between zero-sized objects and one-byte objects.

Yet, at the same time, there _is_ a reason for using inclusive ranges: namely the fact that it seems theoretically possible that an 8 bytes objects be allocated at 0xff[...]ff8 and thus adding 8 would yield 0x0 (overflowing the pointer or usize).

We'll need to move to exclusive ranges, which will require moving to integer space rather than staying in address space, and using bigger integers to avoid overflow. Moving to integer space is probably a good idea regardless, so it's all for the better I guess.

**Comment by matthieu-m** [comment]
Fixed in v0.2.5.

Additionally, v0.2.5 also allows _inner_ ZSTs not to be considered overlapping, since it is sound, though this came at the cost of filtering out ZSTs in `check_distinct`:

```rust
#[test]
fn check_distinct_inner_zst() {
    //  Check that an inner ZST is still considered distinct from its outer instance.
    GhostToken::new(|mut token| {
        let outer = GhostCell::new((1, (), 2));
        let (_, inner, _) = outer.as_tuple_of_cells();

        let tuple = (&outer, inner);
        assert!(tuple.borrow_mut(&mut token).is_ok());
    });
}
```

**Comment by wackbyte** [comment]
Nice! BTW, I think you pushed the v0.2.5 tag, but not the commit itself, so it's not appearing in `master`.

**Comment by matthieu-m** [comment]
_sigh_ I blame `git`'s poor API on that one :'(
